<?php

namespace Application\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Demo_Model_Country extends \Demo_Model_Country implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setCode($sValue)
    {
        $this->__load();
        return parent::setCode($sValue);
    }

    public function setName($sValue)
    {
        $this->__load();
        return parent::setName($sValue);
    }

    public function setContinent($sValue)
    {
        $this->__load();
        return parent::setContinent($sValue);
    }

    public function setRegion($sValue)
    {
        $this->__load();
        return parent::setRegion($sValue);
    }

    public function setSurfaceArea($fValue)
    {
        $this->__load();
        return parent::setSurfaceArea($fValue);
    }

    public function setIndepYear($iValue)
    {
        $this->__load();
        return parent::setIndepYear($iValue);
    }

    public function setPopulation($iValue)
    {
        $this->__load();
        return parent::setPopulation($iValue);
    }

    public function setLifeExpectancy($fValue)
    {
        $this->__load();
        return parent::setLifeExpectancy($fValue);
    }

    public function setGNP($fValue)
    {
        $this->__load();
        return parent::setGNP($fValue);
    }

    public function setGNPOld($fValue)
    {
        $this->__load();
        return parent::setGNPOld($fValue);
    }

    public function setLocalName($sValue)
    {
        $this->__load();
        return parent::setLocalName($sValue);
    }

    public function setGovernmentForm($sValue)
    {
        $this->__load();
        return parent::setGovernmentForm($sValue);
    }

    public function setHeadOfState($sValue)
    {
        $this->__load();
        return parent::setHeadOfState($sValue);
    }

    public function setCapital($iValue)
    {
        $this->__load();
        return parent::setCapital($iValue);
    }

    public function setCode2($sValue)
    {
        $this->__load();
        return parent::setCode2($sValue);
    }

    public function getCode()
    {
        $this->__load();
        return parent::getCode();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getContinent()
    {
        $this->__load();
        return parent::getContinent();
    }

    public function getRegion()
    {
        $this->__load();
        return parent::getRegion();
    }

    public function getSurfaceArea()
    {
        $this->__load();
        return parent::getSurfaceArea();
    }

    public function getIndepYear()
    {
        $this->__load();
        return parent::getIndepYear();
    }

    public function getPopulation()
    {
        $this->__load();
        return parent::getPopulation();
    }

    public function getLifeExpectancy()
    {
        $this->__load();
        return parent::getLifeExpectancy();
    }

    public function getGNP()
    {
        $this->__load();
        return parent::getGNP();
    }

    public function getGNPOld()
    {
        $this->__load();
        return parent::getGNPOld();
    }

    public function getLocalName()
    {
        $this->__load();
        return parent::getLocalName();
    }

    public function getGovernmentForm()
    {
        $this->__load();
        return parent::getGovernmentForm();
    }

    public function getHeadOfState()
    {
        $this->__load();
        return parent::getHeadOfState();
    }

    public function getCapital()
    {
        $this->__load();
        return parent::getCapital();
    }

    public function getCode2()
    {
        $this->__load();
        return parent::getCode2();
    }

    public function getLanguages()
    {
        $this->__load();
        return parent::getLanguages();
    }

    public function getCities()
    {
        $this->__load();
        return parent::getCities();
    }


    public function __sleep()
    {
        return array('__isInitialized__', '_Name', '_Continent', '_Region', '_SurfaceArea', '_IndepYear', '_Population', '_LifeExpectancy', '_GNP', '_GNPOld', '_LocalName', '_GovernmentForm', '_HeadOfState', '_Capital', '_Code2', '_Code', '_Cities');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}