<?php

namespace Application\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Demo_Model_Language extends \Demo_Model_Language implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setCountryCode($sValue)
    {
        $this->__load();
        return parent::setCountryCode($sValue);
    }

    public function setLanguage($sValue)
    {
        $this->__load();
        return parent::setLanguage($sValue);
    }

    public function setIsOfficial($sValue)
    {
        $this->__load();
        return parent::setIsOfficial($sValue);
    }

    public function setPercentage($fValue)
    {
        $this->__load();
        return parent::setPercentage($fValue);
    }

    public function getCountryCode()
    {
        $this->__load();
        return parent::getCountryCode();
    }

    public function getLanguage()
    {
        $this->__load();
        return parent::getLanguage();
    }

    public function getIsOfficial()
    {
        $this->__load();
        return parent::getIsOfficial();
    }

    public function getPercentage()
    {
        $this->__load();
        return parent::getPercentage();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'CountryCode', 'Language', 'IsOfficial', 'Percentage');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}